"""initial schema

Revision ID: 2ae30237f0a2
Revises: 
Create Date: 2026-08-18 16:09:10.648317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae30237f0a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """Create the initial StackHive schema."""
    op.create_table('device_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netbox_id', sa.Integer(), nullable=True),
    sa.Column('manufacturer', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('part_number', sa.String(length=64), nullable=True),
    sa.Column('interface_count', sa.Integer(), nullable=False),
    sa.Column('interface_types', sa.JSON(), nullable=False),
    sa.Column('slot_config', sa.JSON(), nullable=True),
    sa.Column('uplink_slots', sa.Integer(), nullable=False),
    sa.Column('management_interfaces', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manufacturer', 'model', name='uq_device_type_manufacturer_model'),
    sa.UniqueConstraint('netbox_id')
    )
    op.create_table('service_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=64), nullable=False),
    sa.Column('token_encrypted', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('env_key', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_credentials', schema=None) as batch_op:
        batch_op.create_index('ix_service_credential_active', ['is_active', 'service_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_credentials_service_name'), ['service_name'], unique=True)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('configuration_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('device_role', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('git_path', sa.String(length=512), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('git_path'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('configuration_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuration_profiles_device_role'), ['device_role'], unique=False)

    op.create_table('configuration_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('git_path', sa.String(length=512), nullable=False),
    sa.Column('config_section', sa.String(length=64), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'name', name='uq_template_profile_name')
    )
    with op.batch_alter_table('configuration_templates', schema=None) as batch_op:
        batch_op.create_index('ix_template_profile_order', ['profile_id', 'display_order'], unique=False)

    op.create_table('deployment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('git_commit_sha', sa.String(length=40), nullable=False),
    sa.Column('git_branch', sa.String(length=128), nullable=False),
    sa.Column('preview_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('config_diff', sa.Text(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_url', sa.String(length=512), nullable=True),
    sa.Column('pipeline_status', sa.String(length=32), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('deployment_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deployment_records_status'), ['status'], unique=False)

    op.create_table('interface_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('interface_type', sa.String(length=64), nullable=False),
    sa.Column('interface_range', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('git_path', sa.String(length=512), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'name', name='uq_iface_template_profile_name')
    )
    with op.batch_alter_table('interface_templates', schema=None) as batch_op:
        batch_op.create_index('ix_iface_template_profile_order', ['profile_id', 'display_order'], unique=False)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('netbox_id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=64), nullable=False),
    sa.Column('mac_address', sa.String(length=17), nullable=False),
    sa.Column('mgmt_ip', sa.String(length=45), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=False),
    sa.Column('site', sa.String(length=255), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('config_status', sa.String(length=32), nullable=False),
    sa.Column('last_deployment_id', sa.Integer(), nullable=True),
    sa.Column('monitoring_status', sa.String(length=16), nullable=False),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.Column('cloud_managed', sa.Boolean(), nullable=False),
    sa.Column('stale', sa.Boolean(), nullable=False),
    sa.Column('last_netbox_sync', sa.DateTime(), nullable=True),
    sa.Column('grafana_dashboard_uid', sa.String(length=128), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_types.id'], ),
    sa.ForeignKeyConstraint(['last_deployment_id'], ['deployment_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_cloud_managed'), ['cloud_managed'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_config_status'), ['config_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_hostname'), ['hostname'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_netbox_id'), ['netbox_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_devices_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_site'), ['site'], unique=False)

    op.create_table('configuration_variables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('git_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['configuration_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('configuration_variables', schema=None) as batch_op:
        batch_op.create_index('ix_var_scope_device_key', ['scope', 'device_id', 'key'], unique=False)
        batch_op.create_index('ix_var_scope_profile_key', ['scope', 'profile_id', 'key'], unique=False)

    op.create_table('deployment_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deployment_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('config_diff', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployment_records.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deployment_id', 'device_id', name='uq_deployment_device')
    )
    with op.batch_alter_table('deployment_devices', schema=None) as batch_op:
        batch_op.create_index('ix_deployment_device_device', ['device_id'], unique=False)

    op.create_table('ztp_provisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('config_content', sa.Text(), nullable=False),
    sa.Column('script_content', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_meraki', sa.Boolean(), nullable=False),
    sa.Column('git_path', sa.String(length=512), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ztp_provisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ztp_provisions_device_id'), ['device_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_ztp_provisions_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """Drop all tables created by the initial schema."""
    with op.batch_alter_table('ztp_provisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ztp_provisions_status'))
        batch_op.drop_index(batch_op.f('ix_ztp_provisions_device_id'))

    op.drop_table('ztp_provisions')
    with op.batch_alter_table('deployment_devices', schema=None) as batch_op:
        batch_op.drop_index('ix_deployment_device_device')

    op.drop_table('deployment_devices')
    with op.batch_alter_table('configuration_variables', schema=None) as batch_op:
        batch_op.drop_index('ix_var_scope_profile_key')
        batch_op.drop_index('ix_var_scope_device_key')

    op.drop_table('configuration_variables')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_site'))
        batch_op.drop_index(batch_op.f('ix_devices_role'))
        batch_op.drop_index(batch_op.f('ix_devices_netbox_id'))
        batch_op.drop_index(batch_op.f('ix_devices_hostname'))
        batch_op.drop_index(batch_op.f('ix_devices_config_status'))
        batch_op.drop_index(batch_op.f('ix_devices_cloud_managed'))

    op.drop_table('devices')
    with op.batch_alter_table('interface_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_iface_template_profile_order')

    op.drop_table('interface_templates')
    with op.batch_alter_table('deployment_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deployment_records_status'))

    op.drop_table('deployment_records')
    with op.batch_alter_table('configuration_templates', schema=None) as batch_op:
        batch_op.drop_index('ix_template_profile_order')

    op.drop_table('configuration_templates')
    with op.batch_alter_table('configuration_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuration_profiles_device_role'))

    op.drop_table('configuration_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))

    op.drop_table('system_settings')
    with op.batch_alter_table('service_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_credentials_service_name'))
        batch_op.drop_index('ix_service_credential_active')

    op.drop_table('service_credentials')
    op.drop_table('device_types')
    # ### end Alembic commands ###
