#!/usr/bin/env python3
"""Generate Ansible host_vars files for per-device variable overrides.

Reads a CSV with one variable per row and writes host_vars/<hostname>.yml
files (the same layout the dashboard commits to Git).

CSV columns:
    hostname,mgmt_ip,key,value

Example input:
    hostname,mgmt_ip,key,value
    sw-leaf-01,10.0.0.2,iosxe_domain_name,lab.example.com
    sw-leaf-01,10.0.0.2,ntp_servers,"[10.0.1.53, 10.0.1.54]"
    sw-spine-01,10.0.0.1,ospf_area,0.0.0.0

Usage:
    python3 scripts/generate-host-vars.py overrides.csv --out ansible/host_vars
"""
import argparse
import csv
import os
import re
import sys

try:
    import yaml
except ImportError:  # pragma: no cover
    sys.exit("PyYAML is required: pip install pyyaml")

_YAML_KEY_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


def parse_value(raw):
    """Interpret scalars as YAML (ints, bools, lists, dicts) or keep strings."""
    try:
        value = yaml.safe_load(raw)
    except yaml.YAMLError:
        return raw
    if isinstance(value, (dict, list, int, float, bool)) or value is None:
        return value
    return raw


def generate(rows, out_dir):
    """Group CSV rows by hostname and write one host_vars YAML file each."""
    os.makedirs(out_dir, exist_ok=True)
    grouped = {}
    for row in rows:
        hostname = (row.get("hostname") or "").strip()
        key = (row.get("key") or "").strip()
        if not hostname or not key:
            continue
        if not _YAML_KEY_RE.match(key):
            print(f"warning: skipping invalid variable key {key!r} for {hostname}", file=sys.stderr)
            continue
        grouped.setdefault(hostname, {})[key] = parse_value((row.get("value") or "").strip())
    written = []
    for hostname in sorted(grouped):
        path = os.path.join(out_dir, f"{hostname}.yml")
        with open(path, "w") as fh:
            fh.write("# Generated by scripts/generate-host-vars.py (do not edit by hand)\n")
            yaml.safe_dump(grouped[hostname], fh, default_flow_style=False, sort_keys=True)
        written.append(path)
    return written


def main():
    """CLI entry: read the CSV, write host_vars files, report what was written."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("csv_file", help="CSV with columns hostname,mgmt_ip,key,value")
    parser.add_argument("--out", default="ansible/host_vars", help="output directory for host_vars (default: ansible/host_vars)")
    args = parser.parse_args()
    with open(args.csv_file, newline="") as fh:
        rows = list(csv.DictReader(fh))
    written = generate(rows, args.out)
    print(f"wrote {len(written)} host_vars file(s) to {args.out}")
    for path in written:
        print(f"  {path}")


if __name__ == "__main__":
    main()
